site_name: SignDict
theme:
  name: readthedocs
  custom_dir: german_theme
repo_url: http://github.com/signdict/docs
copyright: "<a href='https://signdict.org'>SignDict Dokumentation</a> - Lizenziert unter <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA</a> "
pages:
  - Start: index.md
  - FAQ: faq.md
  - "Deutsche Gebärdensprache": dgs.md
  - "Baby Sign": babysign.md
  - "API": api.md
extra_css: [extra.css]
extra:
  search:
    language: de

